from manim import *
class BooleanOperations(Scene):
    def construct(self):
        ellipse1 = Ellipse(3,5,color=BLUE,fill_opacity=0.5).move_to(LEFT * 5)
        ellipse2 = Ellipse(3,5,color=RED_C,fill_opacity=0.5).move_to(LEFT * 4)
        self.play(FadeIn(ellipse1,ellipse2))
        i = Intersection(ellipse1,ellipse2,fill_opacity=0.5)
        tex = Text("Пересечение")
        tex1 = Text("Группа")
        self.wait(2)
        self.play(FadeIn(i))
        self.wait(1)
        self.play(i.animate.move_to(RIGHT * 5 + UP * 3).scale(0.25))
        self.wait(2)
        self.play(FadeIn(tex))
        self.wait(1)
        self.play(tex.animate.next_to(i,DOWN).scale(0.5))
        self.wait(2)
        gr = Union(ellipse1,ellipse2,fill_opacity=0.5)
        self.play(FadeIn(gr))
        self.wait(2)
        self.play(gr.animate.move_to(RIGHT * 5).scale(0.3))
        self.wait(2)
        self.play(FadeIn(tex1))
        self.wait(1)
        self.play(tex1.animate.next_to(gr,DOWN).scale(0.3))
        self.wait(2)